[tool.poetry]
authors = ["Hannes Krumbiegel"]
description = "Stresses Russian texts and ebooks using ML grammar analysis and Wiktionary data"
license = "GPLv3"
name = "russian-text-stresser"
readme = "README.md"
version = "0.1.0"
repository = "https://github.com/Vuizur/add-stress-to-epub"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta"
]

[tool.poetry.dependencies]
PyQt6 = {version = "^6.3.1", optional = true}
beautifulsoup4 = "^4.11.1"
lxml = "^4.9.1"
mwxml = "^0.3.3"
pymorphy2 = "^0.9.1"
python = "^3.8,<3.11"
spacy = "3.4.0"
stressed-cyrillic-tools = "^0.1.3"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
mypy = "^0.971"
pyinstaller = "^5.3"

[tool.poetry.extras]
GUI = ["PyQt6"]


[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
